clone_folder: c:\gopath\src\github.com\danstis\toggl-taskbar

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

install:
  - choco install gitversion.portable -y
  - rm C:\Tools\GitVersion\GitVersion.exe
  - mkdir %GOPATH%\bin
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version

before_build:
  - gitversion /output buildserver
  - go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo

build_script:
  - ps: goversioninfo -64 -product-version="$env:GitVersion_SemVer" -ver-major="$env:GitVersion_Major" -ver-minor="$env:GitVersion_Minor" -ver-patch="$env:GitVersion_Patch"
  - ps: go build -ldflags "-H=windowsgui -X main.Version=$env:GitVersion_SemVer" github.com/danstis/toggl-taskbar

test_script:
  - go vet ./...

after_test:
  - ps: mkdir ".\package\"
  - ps: Copy-Item .\config.toml.default .\package\config.toml
  - ps: Copy-Item .\assets .\package\ -Recurse -Force
  - ps: Get-ChildItem -Path .\* -Include "*.exe","*.md","LICENSE" -Force | Copy-Item -Destination .\package
  - 7z a toggl-taskbar.zip %APPVEYOR_BUILD_FOLDER%\package\*

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: toggl-taskbar.zip
    name: toggl-taskbar

deploy:
  release: v$(GitVersion_SemVer)
  description: ""
  provider: GitHub
  auth_token:
    secure: W3T3l8qHO8zyWmXx72+sdErNqCEfFVa/MEu4FAq8EUiI2SrLeQhTE8Ff4ts5avlO # GitHub Token
  artifact: toggl-taskbar
  force_update: false
  draft: false
  prerelease: false
  on:
    branch: master
    # appveyor_repo_tag: true # deploy on tag push only
