# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
    ldflags:
      - -H=windowsgui -X main.Version={{.Version}}
    mod_timestamp: "{{.CommitTimestamp}}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{.Tag}}-snapshot#{{.Commit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^(build|chore|ci|doc|docs|none|perf|refactor|skip|test)(\(.*?\))?:\s?'
