# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # Get goreleaser
    - go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
    - go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
    - cp ./config.toml.default ./config.toml
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
    ldflags:
      - -H=windowsgui -X main.Version={{.Version}}
    mod_timestamp: "{{.CommitTimestamp}}"
    ignore:
      - goarch: arm64
archives:
  - format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{.Version}}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - "assets/*"
      - "*.md"
      - "LICENSE"
      - "config.toml"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{.Tag}}-snapshot#{{.Commit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^(build|chore|ci|doc|docs|none|perf|refactor|skip|test)(\(.*?\))?:\s?'
