name: Build and Release

on:
  push:
    branches:
      - master
      - main
      - beta
      - "feature/*"
      - "fix/*"
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
  build:
    name: Release
    runs-on: windows-2019
    needs: [golangci]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: "5.x"

      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.9

      - name: Push version tag # https://github.com/marketplace/actions/commit-tagger
        uses: tvdias/github-tagger@v0.0.2
        continue-on-error: true
        if: ${{ steps.gitversion.outputs.PreReleaseTagWithDash == '' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.gitversion.outputs.FullSemVer }}

      - name: Check out code
        uses: actions/checkout@v2
        if: ${{ steps.gitversion.outputs.PreReleaseTagWithDash == '' }}
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2 # https://github.com/marketplace/actions/goreleaser-action
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
